---
name: instant-https

releases:
- name: "bpm"
  version: "0.8.0"
  url: "https://bosh.io/d/github.com/cloudfoundry-incubator/bpm-release?v=0.8.0"
  sha1: "0cf53162bb246de6afb4c1eaf14becdb7865a217"
- name: instant-https
  version: latest

stemcells:
- alias: default
  os: ubuntu-trusty
  version: latest

addons:
- jobs:
  - name: bpm
    release: bpm
  name: bpm

instance_groups:
- name: https_proxy
  azs: [z1]
  instances: 1
  vm_type: micro
  stemcell: default
  persistent_disk: 10240
  networks:
  - name: default
  jobs:
  - name: proxy
    release: instant-https
    properties:
      contact_email: ((contact_email))
      dns_providers: ((dns_providers))
      caddyfile: ((caddyfile))

update:
  canaries: 1
  canary_watch_time: 1000-60000
  max_in_flight: 1
  update_watch_time: 1000-60000
